
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_media_hub
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat_db
      
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE